DARK_ROAST_COFFEE_COST = 34
HOUSE_BLEND_COFFEE_COST = 56
DECAF_COFFEE_COST = 44
ESPRESSO_COFFEE_COST = 12

BLACK_TEA_COST = 10
GREEN_TEA_COST = 13

CONDIMENT_MILK_COST = 6
CONDIMENT_MOCHA_COST = 3
CONDIMENT_SOY_COST = 9
CONDIMENT_WHIP_COST = 5
CONDIMENT_CARAMEL_COST = 2
